<h2>Setting up imports and helper functions...</h2>
These helper functions will allow us to have padded matricies if they aren't square.

In [95]:
import random
import numpy as np
print(np.__version__)

# checks if matrix is square
def isSquareMtx(array):
  return (array.shape[0] == array.shape[1])

# checks array if it needs padding
# returns tuple of dimensions, and if they're square
def checkIfNeedPad(array):
  lesser = 2
  if (array.shape[0] == array.shape[1]):
    sq = True
  else:
    if (array.shape[0] < array.shape[1]):
      lesser = 0
    elif (array.shape[0] > array.shape[1]):
      lesser = 1
    sq = False
  return array.shape[0], array.shape[1], sq, \
    abs(array.shape[0] - array.shape[1]), lesser

# paddes the matrix
def padMtx(array):
  newshape, padarr = (), []
  (arrshape_0, arrshape_1, isSquare, diff, lessloc) = checkIfNeedPad(test)
  # check if the array is not square
  if (not isSquare and lessloc != 2):
    newshape = (arrshape_0 + diff if lessloc == 0 else arrshape_0 \
                , arrshape_1 + diff if lessloc == 1 else arrshape_1)
    # creating new array with square, padded sides
    padarr = np.zeros(newshape)
    # copying over old data
    padarr[:array.shape[0],:array.shape[1]] = array
  else:
    padarr = array
  return padarr.astype(int)

1.18.2


<h2>...Creating convolution functionality...</h2>

In [0]:
# convolution functionality
def conv2d(input_mat, kernel_mat):
  # checking if both matricies are not square
  if (not isSquareMtx(input_mat)):
    padMtx(input_mat)
  if (not isSquareMtx(kernel_mat)):
    padMtx(kernel_mat)
  # checking if kernel matrix is greater than input matrix
  if (kernel_mat.shape > input_mat.shape):
    return print("Error: Kernel matrix greater than input matrix. "\
                 "Exiting from function.")
  
  # flipping kernel to do convolution
  kernel_mat = np.flip(kernel_mat)
  # grabbing data for convolution
  y, x = input_mat.shape
  ky, kx = kernel_mat.shape
  y = y - ky + 1
  x = x - kx + 1
  output_mat = np.zeros((y,x))
  
  # loop through input matrix
  for i in range(y):
    for j in range(x):
      # convolution = multiply kernel mtx. by kernel-sized piece of input mtx.
      # sum up all values there and put them in indv. value of output mtx.
      output_mat[i][j] = np.sum(kernel_mat * input_mat[i:i+ky, j:j+kx])
  return output_mat

<h2>...And testing the code above.</h2>
This code was grabed from a TA for this class. 

[Link to TA's code](https://colab.research.google.com/drive/1MIoNq4_xglLesBF1kdWJelP2CmdPuYbv)

In [97]:
from scipy import signal
import numpy as np

input_mat = []
kernel_mat = []
expected_mat = []

# test case 1
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 1, 2, 1],
                      [1, 2, 1, 2],
                      [2, 1, 2, 1]]))

kernel_mat.append(np.array([[1, 0],
                       [0, 1]]))

expected_mat.append(np.array([[2, 4, 2],
                                [4, 2, 4],
                                [2, 4, 2]]))

# test case 2
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0], [0, 1]]))
expected_mat.append(np.array([[2, 0, 0], [0, 2, 0], [0, 0, 2]]))


# test case 3
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, -1],
                       [-1, 0]]))

expected_mat.append(np.array([[ 1, -1,  0], [-1,  1, -1],[ 0, -1,  1]]))


# test case 4
input_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append(np.array([[4]]))


# test case 5 - should either through an error, or return empty matrix
input_mat.append(np.array([[1, -1],
                       [-1, 0]]))
kernel_mat.append(np.array([[1, 0, 0, 0],
                      [0, 1, 0, 0],
                      [0, 0, 1, 0],
                      [0, 0, 0, 1]]))

expected_mat.append([])



for i in range(len(input_mat)):
  # uncomment line for student code testing
  output_mat = conv2d(input_mat[i], kernel_mat[i])

  # uncomment lines below (and comment line above) for generating test cases.
  if input_mat[i].shape[0] < kernel_mat[i].shape[0]:
    output_mat = []
  else:
    output_mat = signal.convolve2d(input_mat[i], kernel_mat[i], mode='valid')

  print(output_mat)
  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!\n")
  else:
    print("Incorrect output!\n")

[[2 4 2]
 [4 2 4]
 [2 4 2]]
Correct output!

[[2 0 0]
 [0 2 0]
 [0 0 2]]
Correct output!

[[ 1 -1  0]
 [-1  1 -1]
 [ 0 -1  1]]
Correct output!

[[4]]
Correct output!

Error: Kernel matrix greater than input matrix. Exiting from function.
[]
Correct output!

