<h2>Setting up imports and helper functions...</h2>
These helper functions will allow us to have padded matricies if they aren't square. Similar to HW#4Problem#1's helper functions.

In [34]:
import random
import numpy as np
print(np.__version__)

# checks if matrix is square
def isSquareMtx(array):
  return (array.shape[0] == array.shape[1])

# checks array if it needs padding
# returns tuple of dimensions, and if they're square
def checkIfNeedPad(array):
  lesser = 2
  if (array.shape[0] == array.shape[1]):
    sq = True
  else:
    if (array.shape[0] < array.shape[1]):
      lesser = 0
    elif (array.shape[0] > array.shape[1]):
      lesser = 1
    sq = False
  return array.shape[0], array.shape[1], sq, \
    abs(array.shape[0] - array.shape[1]), lesser

# paddes the matrix
def padMtx(array):
  newshape, padarr = (), []
  (arrshape_0, arrshape_1, isSquare, diff, lessloc) = checkIfNeedPad(test)
  # check if the array is not square
  if (not isSquare and lessloc != 2):
    newshape = (arrshape_0 + diff if lessloc == 0 else arrshape_0 \
                , arrshape_1 + diff if lessloc == 1 else arrshape_1)
    # creating new array with square, padded sides
    padarr = np.zeros(newshape)
    # copying over old data
    padarr[:array.shape[0],:array.shape[1]] = array
  else:
    padarr = array
  return padarr.astype(int)

1.18.2


<h2>...Creating maxpooling functionality...</h2>

In [35]:
# maxpooling functionality
def maxpooling2d(input_mat, s):
  # checking if input matrix is not square
  if (not isSquareMtx(input_mat)):
    padMtx(input_mat)
  # checking if pool matrix is going to be greater than input matrix
  smatshape = (s, s)
  if (smatshape > input_mat.shape):
    return print("Error: Pool matrix greater than input matrix. "\
                 "Exiting from function.")
    
  # Assume stride = s (can be independent from window shape, however)
  stride = s
  # building pool matrix
  y, x = input_mat.shape
  output_mat = np.zeros((int(y / s), int(x / s)))
  y = y - s + 1
  x = x - s + 1
  # loop through input matrix
  for i in range(0, y, s):
    for j in range(0, x, s):
      # in every s region of the input matrix, find the max 
      # then output to the final matrix   
      output_mat[int(i / s)][int(j / s)] = np.amax(input_mat[i:i+s, j:j+s])

  return output_mat.astype(int)

test = np.array([[1, 2, 1, 2], [2, 4, 2, 1], [1, 2, 4, 2], [2, 1, 2, 1]])
print("Test array = ", test)
print("Test results = ", maxpooling2d(test, 2))

Test array =  [[1 2 1 2]
 [2 4 2 1]
 [1 2 4 2]
 [2 1 2 1]]
Test results =  [[4 2]
 [2 4]]


<h2>...And testing the code above.</h2>
This code was grabed from a TA for this class. 

[Link to TA's code](https://colab.research.google.com/drive/1MIoNq4_xglLesBF1kdWJelP2CmdPuYbv)

In [36]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")

[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
Correct output!
